use_frameworks!

platform :ios, '10.0'

target 'ZLYYSwift_Example' do
  pod 'ZLYYSwift', :path => '../'

  target 'ZLYYSwift_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
